### ISSUE TITLE
Auto与CoudUri相关

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/fc-alibaba-component#51]
Nas部分配置变更：
```
Nas: Auto
  
Nas: 
  Type: Auto
  FcDir: /home/ssss
  LocalDir: 
     - ./ssss
     - ./sdddd

Nas:
    UserId: userID
    GroupId: groupID # s nas sync
    MountPoints:
      - Alias: demo # 选填
        NasAddr: 3e3544a894-qjf60.cn-shanghai.nas.aliyuncs.com
        NasDir: /demo
        FcDir: /home/ssss
        LocalDir: ./ssss
      - NasAddr: 3e3544a894-qjf60.cn-shanghai.nas.aliyuncs.com
        NasDir: /demo
        FcDir: /home/aaaaaa
        LocalDir: 
          - ./ssss
          - ./sdddd
```

CodeUri变更：
```
1. CodeUri: 目录
2. CodeUri: 
         Src: 目录
         Exclude: 
              - 目录
         Include: 
              - 目录
3. CodeUri: 
         Bucket: 目录
         Src: 目录
         Exclude: 
              - 目录
         Include: 
              - 目录
4. CodeUri: 
         Bucket: ----
         Object: -----
```

逻辑变更：
1: Nas的格式配置， 按照上面的写的
2: deploy的时候，auto帮助用户覆盖yaml，但是可以通过--skip-sync不覆盖（log，nas，vpc）
3: deploy的时候，自动帮助用户剔除目录
4: sync，和auto反写，要注意一个yaml多个项目的问题
